### ISSUE TITLE
hide everything except default icon on boot

### ISSUE THREAD

**Issue by fragolinux** [UHDbits/M73-Tiny-OpenCore#15]
no issue, just a suggestion:
I added this to my plist, to hide everything except the default boot icon (for the others, just press space to unhide):

**Misc > Security > ScanPolicy = 17760515: Hide EFI from OC boot menu (this is the OC default and had previously been set to 0 which shows all).** 

took this from this [page](https://www.insanelymac.com/forum/topic/343937-guide-catalina-big-sur-monterey-ventura-on-hp-elitedesk-800-g4g5-mini-the-perfect-macmini81-hackintosh/?do=findComment&comment=2802277), there's an other option there, but as I was just sawing the efi icon, that line solved my issue

**Comment by UHDbits** [comment]
Okay, so I may have just found a way to hide the EFI boot entry (using .contentVisibility). I can't test this right now but I will try to test it soon. Thanks for reporting this, becauseI was researching this a while ago but ended up not finding an answer, but hopefully, this way will work.

**Comment by UHDbits** [comment]
I have just committed the files, so I will try them once I get home.

**Comment by fragolinux** [comment]
but this just hides the entries, if you press space they're still all there, isn't this enough?
btw, i manually did this many times, but yesterday i just binned old efi folder and replaced with your latest one (after changing the serial and usual stuff), and i had the efi icon back... i didn't remember how i removed those, i had to compare the 2 xml files again, then i remembered that other thread i use on my other hackintosh... thanks for your work!

**Comment by fragolinux** [comment]
oh, right, and in that same page talks about contentVisibility, right :)

**Comment by UHDbits** [comment]
I already have "HideAuxiliary" enabled in the configuration, but that seems to keep the "EFI" partition listed in the bootloader. I do think that the contentVisibility should be able to hide it.

I know that the EFI partition used to be hidden in OpenCore by default, but when the version with .contentVisibility was released, I saw the files inside of the OpenCorePkg download, but I never ended up adding them because I didn't know what they were for. Well, it seems like in that release, they made it so that you have to have contentVisibility in the EFI partition to hide the entry, which is why the EFI partition now shows. Again, hopefully, the latest commit should fix this but I will double-check once I get home. If it's fixed, I'll close this issue.

Thanks for reporting and thanks for appreciating my work! I hope it has and will continue to work well for you.
