### ISSUE TITLE
An issue about displaying 4k resolution

### ISSUE THREAD

**Issue by qqhpc** [UHDbits/M73-Tiny-OpenCore#16]
Which do you have: an M73 Tiny or an M93p?:
M93p

Do your specifications match the ones shown in the README.md? (not including the USB WiFi adapter):
There are differences, my cpu is i5-4690T, I have not installed wireless network card and bluetooth

If your specifications do not match, what are your specifications?:
My cpu is i5-4690T, I have not installed wireless network card and bluetooth

What version of OS X/macOS are you using?:
The version I am using is macOS Monterey 12.6.5

What is your issue?:
Although I can happily experience macOS on a 4k TV, the state of the screen is very unstable: first the screen will flicker, then the screen will go black without any video output, and finally it will return to normal, repeating non-stop. If I drop the resolution to 1080p, the screen becomes normal.

Steps to reproduce your issue:
Adjust the resolution to 4k 30hz

Other supplementary information: The video output interface of my computer is a dp interface, and the computer and the TV are connected by a dp-to-hdmi cable. It is currently confirmed that this set of equipment can normally display 4k 30hz images under windows10.

**Comment by UHDbits** [comment]
Mhm, 4K seems to cause a lot of issues on this computer (and Hackintoshes in general). I don't have much guidance to help you with right now, as I've tried to do some research and haven't come up with much, and I've been pretty busy lately, but I hope that I can try to help you as soon as I can. One of the most likely issues seems like it's possible that the connector-types may need to be patched for a DP-to-HDMI adapter, but I'm still not 100% sure if that is the issue, and if it is, I'm not sure if I could merge it into main without breaking normal DP support.

Sorry that I don't have any more information or anything for you to test right now, but I hope that I can try to send you something in the next week or so. Thanks for reporting this issue!

**Comment by UHDbits** [comment]
Okay, so I have a version that might be able to fix your issue, but I'm not sure yet if the port number is right (not by my ThinkCentre right now, so I can't double check the DisplayPort port number, but I will check once I get home), and of course it's possible this could just not solve your issue in the first place. I'll check the port number on my ThinkCentre as soon as I can, and I'll comment here if I find out the port I put in the configuration is wrong, and upload an updated version.

Pretty much, the changes I made spoof the DisplayPort port as an HDMI port, which might be able to solve your issue. I see that this does sometimes happen with DP to HDMI adapters and that this needs to be done, but usually, there's not output no matter what, or glitchy output no matter what resolution, but I figure this change is a good first test. Here's the link to the EFI: [EFI.zip](https://github.com/UHDbits/M73-Tiny-OpenCore/files/11491839/EFI.zip)

Also, thanks a lot for your comment above, people like you make me want to continue maintaining this OpenCore configuration!

**Comment by UHDbits** [comment]
Also, I recommend testing these configurations on a USB drive before uploading the configurations to your EFI partition on your internal storage, because it's always possible these changes cause there to be no output at all, and it's insanely annoying to edit the EFI partition from Windows. You can format a USB drive just for EFI by looking at [this link](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html) and the "Rufus" section, and this will allow you to edit the EFI from Windows in case you are unable to use macOS.

**Comment by UHDbits** [comment]
Ah, and I just found out the M93p has two DisplayPort ports, so if one of them still has the issue with this configuration, you should try the other one and see if that works, because I'm not sure if the port number on the M73 Tiny would be the same on the M93p.

**Comment by UHDbits** [comment]
Huh, yeah, that is interesting, it does seem like the ports vary between models (sometimes it's HDMI, sometimes it's nothing). Thanks for testing the configuration that I sent you, I'll try to send another one with other changes tommorow.

Also, if we are unable to solve this issue, you are able to improve the experience by trying to use 1440p60 on the TV that you are using. If it doesn't show up already in macOS, you can usually manually force a resolution using a program like SwitchResX, BetterDisplay, or RDM. Do note that this has the possibility to soft-brick your macOS install, and you may have to run some terminal commands to fix it, or may just need to reinstall (don't ask me how I know that). Of course, this doesn't completely solve your issue, so I'll try to provide more files tomorrow. Thanks for testing the configuration that I sent above!

**Comment by UHDbits** [comment]
Okay, I'm very sorry it's taken me so long, but some other stuff came up for school, but school is ending very soon so I should be free from now on!

I'm starting to wonder if it's possible that the ThinkCentre is trying to output at 4K60, which is overloading the HDMI connection and causing those flashes. Have you checked in System Preferences/System Settings to make sure the refresh rate is set to 30hz? (Normally, I'm pretty sure a 30hz option doesn't even show, but it should in this case.)

**Comment by UHDbits** [comment]
I'm starting to think that maybe patching BusIDs (https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html#mapping-the-video-ports) could help to solve this issue, as the iMac18,1 doesn't natively have an HDMI-out, so even though we have patched the connector type, it could still be trying to output like a DisplayPort port. I'm once again sadly not by my ThinkCentre right now, and it seems like this would be easier with my ThinkCentre, but it should be possible without, so I'll try to send you another EFI soon.

**Comment by UHDbits** [comment]
Okay, so I haven't gotten to the point of BusIDs yet, because I've looked at them and it seems like there is a lot of troubleshooting that might be involved to get it to the correct one, so instead, I've started by patching all of the connections to spoof as HDMI. Before, I was just patching "con1", but we also have "con0" and "con2" that can be patched, so I've patched all three of them. If this still doesn't work, then we will move onto BusIDs, but that might require a lot of steps.

Here is the EFI file, as mentioned before, please be careful and make sure to boot this EFI from a flash drive. 
[EFI.zip](https://github.com/UHDbits/M73-Tiny-OpenCore/files/11640353/EFI.zip)

**Comment by UHDbits** [comment]
Mhm, if you aren't that concerned about the issue and don't want it fixed, then I'm fine with stopping work on it. I do want you to realize that I really don't mind helping out with issues like this, and I enjoy troubleshooting and finding out issues. But of course, if you aren't worried about it, then I'm fine to stop. If anyone experience the same issue, then they can reopen this issue and I can continue working on it.

Although, I would like to suggest a couple of possible fixes to your problem. These will either make the issue slightly better, or completely resolve them.

1. Buy an active DisplayPort to HDMI adapter. It seems like these usually tend to work better with macOS, but it's still possible that it may not fix your issue (it's also possible that you already have an active adapter). Some active adapters may also allow you to run 4K60 instead of 4K30, depends on your display's input.
2. Run the display at 1440p60. This is a good balance between 4K30 and 1080p60, because with this, you are able to run at 60FPS at a pretty decent resolution. To do this, if you don't have a 1440P option in your "Displays" preferences, you can use an app like [SwitchResX (paid)](https://www.madrau.com), [BetterDisplay (freemium)](https://github.com/waydabber/BetterDisplay#readme), or [RDM (free)](https://github.com/usr-sse2/RDM). As mentioned, this should offer a decent balance. I should note I've had issues setting custom display resolutions on macOS before, and I haven't been able to recover from the black screens that they have caused (although, this usually only happens when I am trying to get a custom HiDPI resolution working), so I recommend backing up any important data before trying these methods, even though you should theoretically be able to recover from them.

I'd like to thank you for being so civil in this issue, and being so understanding with my sometimes delayed responses. Like mentioned before, people like you make me want to continue working on this OpenCore configuration! If you are satisfied and don't want to worry about the issue, feel free to close it.
